### ISSUE TITLE
can't apply args

### ISSUE THREAD

**Issue by nhamhuynh79** [Distance10086/pve-patch#1]
Hi, how to set args to spoof smbios, I cant apply these args:
-cpu host,+kvm_pv_unhalt,+kvm_pv_eoi,hv_spinlocks=0x1fff,hv_vapic,hv_time,hv_reset,hv_vpindex,hv_runtime,hv_relaxed,kvm=off,hv_vendor_id=intel,vmware-cpuid-freq=false,enforce=false,host-phys-bits=true,hypervisor=off -smbios type=0,version=UX305UA.201 -smbios type=1,manufacturer=ASUS,product=UX305UA,version=2021.1 -smbios type=2,manufacturer=Intel,version=2021.5,product='Intel i9-12900K' -smbios type=3,manufacturer=XBZJ -smbios type=17,manufacturer=KINGSTON,loc_pfx=DDR5,speed=4800,serial=114514,part=FF63 -smbios type=4,manufacturer=Intel,max-speed=4800,current-speed=4800

**Comment by Distance10086** [comment]
You can refer to this file to set  smbios args.
https://github.com/Distance10086/pve-patch/blob/main/pve-qemu/smbios.c
